version: '3.8'

services:
  php81:
    image: php:8.1-cli
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    command: bin/phpunit

  php82:
    image: php:8.2-cli
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    command: bin/phpunit

  php83:
    image: php:8.3-cli
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    command: bin/phpunit
