name: Build
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '5.6'
          - '7.0'
          - '7.4'
    name: PHP ${{ matrix.php-version }} sample
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - run: |
          curl -s http://getcomposer.org/installer | php
          php composer.phar install
      - env:
          CONVERT_API_SECRET: ${{ secrets.CONVERTAPI_SECRET }}
        run: bin/phpunit
